# -*- coding: utf-8 -*-
"""Banking Fraud Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kR_suimhmdNxXux_9RkI7a4rrf9bGwK-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("banking_fraud_dataset.csv")
df.head()

df.describe()

df.isnull().sum()

df.duplicated().sum()

# Replace missing values with "No Fraud"

df["Fraud_Indicators"] = df["Fraud_Indicators"].fillna("No Fraud")

df["Fraud_Type"] = df["Fraud_Type"].fillna("No Fraud")

print("Missing values handled successfully!")

# Count fraud and non-fraud transactions
df["Fraud_Flag"].value_counts()

#Fraud Distribution Visualz

plt.figure(figsize=(4,2))

sns.countplot(data=df, x="Fraud_Flag")
plt.title("Distribution of Fraudulent vs Non-Fraudulent Transactions")
plt.xlabel("Fraud Flag (0 = No Fraud, 1 = Fraud)")
plt.ylabel("Number of Transactions")

plt.show()

#Transactional Amount Distribution

plt.figure(figsize=(4,2))

sns.histplot(df["Amount"], bins=30)
plt.title("Distribution of Transaction Amounts")
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")

plt.show()

#Boxplot of Transaction Amount
plt.figure(figsize=(4,2))

sns.boxplot(x=df["Amount"])
plt.title("Boxplot of Transaction Amount")

plt.show()

#Transaction Type

df["Transaction_Type"].value_counts()
plt.figure(figsize=(4,2))

sns.countplot(data=df, x="Transaction_Type")
plt.title("Number of Transactions by Type")
plt.xticks(rotation=45)

plt.show()

#Fraud By Transaction Type

plt.figure(figsize=(5,3))

sns.countplot(data=df,
              x="Transaction_Type",
              hue="Fraud_Flag")

plt.title("Fraud by Transaction Type")
plt.xticks(rotation=45)

plt.show()

#Customer Age Distribution

plt.figure(figsize=(4,2))

sns.histplot(df["Customer_Age"], bins=20)

plt.title("Distribution of Customer Age")

plt.show()

# Selecting only numeric columns
numeric_df = df.select_dtypes(include=['number'])

# Displaying  the first few rows
numeric_df.head()

# Calculating the correlation matrix
correlation_matrix = numeric_df.corr()

# Displaying it
correlation_matrix

plt.figure(figsize=(4,2))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f")

plt.title("Correlation Heatmap")
plt.show()

# Count fraudulent and non-fraudulent transactions

df["Fraud_Flag"].value_counts()

#AVG fraud Amount by Status
df.groupby("Fraud_Flag")["Amount"].mean()

#Fraud by Transaction Type
pd.crosstab(df["Transaction_Type"], df["Fraud_Flag"])

merchant_fraud = pd.crosstab(df["Merchant_Category"],
                             df["Fraud_Flag"])

merchant_fraud

plt.figure(figsize=(4,2))

sns.boxplot(data=df,
            x="Fraud_Flag",
            y="Amount")

plt.title("Transaction Amount by Fraud Status")
plt.xlabel("Fraud Flag")
plt.ylabel("Transaction Amount")

plt.show()

#Which transaction types have the highest average transaction amount?

transaction_avg = df.groupby("Transaction_Type")["Amount"].mean().sort_values(ascending=False)

transaction_avg

df.to_csv("cleaned_banking_fraud.csv", index=False)

print("✅ Cleaned dataset saved successfully!")

from google.colab import files

files.download("cleaned_banking_fraud.csv")